module.exports = {
    ".txt": "txt/plain", 
    ".html": "text/html",
    ".css": "text/css",
    ".js": "text/javscript",
    ".json": "application/json",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".png": "image/png",
    ".PNG": "image/PNG",
    ".bmp": "image/bmp",
    ".tiff": "image/tiff",
    ".svg": "image/svg",
}